version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel
    depends_on:
      - php
      - mysql
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
  ngrok:
    image: ngrok/ngrok:latest
    command: http nginx:80 --host-header="nginx:80"
    depends_on:
      - nginx
    ports:
      - "4040:4040"     # WEB‑UI
      - "443:443"       # HTTPS
      - "80:80"         # HTTP
    environment:
      NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
